version: '3.8'

services:
  redis:
    image: redis:6  
    ports:
      - "6379"

  python:
    image: python:3.9-slim
    volumes:
      - .:/app
    ports:
      - "5000" 
    depends_on:
      - redis